server.port=8081

spring.application.name=client
spring.security.oauth2.client.registration.project-report-client.client-id=${PROJECT_CLIENT_ID:project-report-client}
spring.security.oauth2.client.registration.project-report-client.client-secret=${PROJECT_CLIENT_SECRET}
spring.security.oauth2.client.registration.project-report-client.provider=keycloak
spring.security.oauth2.client.registration.project-report-client.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.project-report-client.scope=project:read
spring.security.oauth2.client.provider.keycloak.token-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8090/auth/realms/tutorial}/protocol/openid-connect/token
